### ISSUE TITLE
pullRequestTableContainer overflowing page when many Pull Requests

### ISSUE THREAD

**Issue by rickjerrity** [sierpinski/Blitz#25]
We use your extension with VSTS, and it seems like the latest update to this extension has a problem where the scrolling div overflows past the bottom of the screen when there are many active pull requests out. The issue seems to be with the CSS for pullRequestTableContainer, specifically the `height`.

In my tests, it seems like setting the height to the following fixed the issue:

`height: calc(100% - 80px)`

(80px is the combined height of the two VSTS toolbars)

I forked the branch and could make a pull request if wanted. I'm not sure if this change will negatively impact the use of this extension with TFS, as I am unable to test that. Cheers!

**Comment by sierpinski** [comment]
Please send a PR and I'll take a look. Appreciate the help.

**Comment by sierpinski** [comment]
You know, I see you put the code right there. Let me just go ahead and take a look, save some time.

**Comment by sierpinski** [comment]
I believe this is fixed as of v. 1.0.2. I made some spacing changes. Please confirm.

**Comment by rickjerrity** [comment]
That seems to have fixed the issue when I access it using Chrome, but the issue still exists in Firefox. Doing some more research, it appears that Firefox needs to have the `body` height set to 100% also in order for it to use `calc`. Adding `height: 100%` to the body tag resolves the issue in both Firefox and Chrome. 

Aside from that, the issue does still occur if you click the blue `options` button, but that is not a big deal as you can simply hit the button again to close the section. Nice work on the quick fixes though, one last patch should fix it up! :)

**Comment by sierpinski** [comment]
Thanks for the great research and help. I added the body css you suggested in 1.0.3. Mind checking it out in Firefox?

Edit: I fixed the options button table spacing issue in version 1.0.4.

**Comment by rickjerrity** [comment]
Very nice, everything seems to be working in both Chrome and Firefox, including the options fix you made. Thanks for the fast work!
